
cc_test(
    name = "test",
    srcs = ["test.cpp"],
    deps = [
         "//calculator:functionalities" ,
         "@com_google_googletest//:gtest",
         "@com_google_googletest//:gtest_main",
    
    ],
    visibility = ["//visibility:public"],
)
